# Generated by Django 5.1.3 on 2024-12-08 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('pipeline_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_plan', models.BooleanField(default=False)),
                ('site_photos', models.BooleanField(default=False)),
                ('requirements_checklist', models.BooleanField(default=False)),
                ('pdf_upload', models.FileField(blank=True, null=True, upload_to='pipelines/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_details', to='customers.customer')),
            ],
        ),
    ]
