# Generated by Django 5.1.3 on 2025-01-16 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_document_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPhase',
            fields=[
                ('designphase_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.BooleanField(default=False)),
                ('quotation', models.BooleanField(default=False)),
                ('design', models.BooleanField(default=False)),
                ('submit_to_client', models.BooleanField(default=False)),
                ('client_feedback', models.BooleanField(default=False)),
                ('schedule_client_meeting', models.DateField(blank=True, null=True)),
                ('design_and_amount_freeze', models.BooleanField(default=False)),
                ('create_client_grp', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_phases', to='customers.customer')),
            ],
        ),
    ]
