# Generated by Django 5.1.3 on 2025-08-25 14:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_remove_projectlineitemaccessory_accessory_and_more'),
        ('customers', '0008_remove_customer_kitchen_kitchentype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('role', models.CharField(choices=[('CABINET', 'CABINET'), ('DOOR', 'DOOR'), ('TOP', 'TOP'), ('BOTH', 'BOTH')], default='BOTH', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CabinetTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_depth', models.PositiveIntegerField(default=600, help_text='Default depth in mm')),
                ('category', models.ForeignKey(blank=True, help_text='Category this cabinet type belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Cabinet Types',
            },
        ),
        migrations.CreateModel(
            name='GeometryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('formula_cabinet_sqft', models.TextField()),
                ('formula_door_sqft', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('cabinet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geometry_rules', to='pricing.cabinettypes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('budget_tier', models.CharField(choices=[('LUXURY', 'LUXURY'), ('ECONOMY', 'ECONOMY')], max_length=10)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=5)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('QUOTED', 'QUOTED'), ('CONFIRMED', 'CONFIRMED'), ('IN_PRODUCTION', 'IN_PRODUCTION'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=20)),
                ('scopes', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING')], default='OPEN', max_length=10)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('width_mm', models.PositiveIntegerField()),
                ('depth_mm', models.PositiveIntegerField()),
                ('height_mm', models.PositiveIntegerField()),
                ('computed_cabinet_sqft', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('computed_door_sqft', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('cabinet_unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('door_unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cabinet_material_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('standard_accessory_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('door_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('top_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('line_total_before_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('remarks', models.TextField(blank=True)),
                ('cabinet_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_cabinet_material', to='pricing.materials')),
                ('cabinet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.cabinettypes')),
                ('door_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_door_material', to='pricing.materials')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricing.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLineItemAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_rate_snapshot', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.accessories')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_accessories', to='pricing.projectlineitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='projects/plans/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_images', to='pricing.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subtotal_cabinets', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('subtotal_doors', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('subtotal_accessories', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('subtotal_tops', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='pricing.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CabinetTypeBrandCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('standard_accessory_charge', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('cabinet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_charges', to='pricing.cabinettypes')),
            ],
            options={
                'verbose_name': 'Cabinet Type Brand Charge',
                'verbose_name_plural': 'Cabinet Type Brand Charges',
                'unique_together': {('cabinet_type', 'brand_name', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='FinishRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('budget_tier', models.CharField(choices=[('LUXURY', 'LUXURY'), ('ECONOMY', 'ECONOMY')], max_length=10)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cabinet_rates', to='pricing.materials')),
            ],
            options={
                'unique_together': {('material', 'budget_tier', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='DoorFinishRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='door_rates', to='pricing.materials')),
            ],
            options={
                'unique_together': {('material', 'effective_from')},
            },
        ),
    ]
