# Generated by Django 5.1.3 on 2025-08-26 06:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('budget_tier', models.CharField(choices=[('LUXURY', 'LUXURY'), ('ECONOMY', 'ECONOMY')], max_length=10)),
                ('calc_method', models.CharField(choices=[('PER_WIDTH', 'Per Cabinet Width (mm)'), ('PER_LM', 'Per Linear Meter'), ('FLAT_RATE', 'Flat Rate per Cabinet'), ('WALL_ONLY', 'Wall Cabinets Only')], max_length=20)),
                ('led_strip_rate_per_mm', models.DecimalField(decimal_places=4, default=Decimal('0.75'), max_digits=10)),
                ('spot_light_rate_per_cabinet', models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10)),
                ('led_specification', models.TextField(blank=True)),
                ('spot_light_specification', models.TextField(blank=True)),
                ('applies_to_wall_cabinets', models.BooleanField(default=True)),
                ('applies_to_base_cabinets', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('cabinet_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.materials')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_top_length_mm', models.IntegerField(help_text='Manual input for work top length')),
                ('total_wall_cabinet_width_mm', models.IntegerField(default=0)),
                ('total_base_cabinet_width_mm', models.IntegerField(default=0)),
                ('wall_cabinet_count', models.IntegerField(default=0)),
                ('led_under_wall_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('led_work_top_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('led_skirting_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spot_lights_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_lighting_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('lighting_tier', models.CharField(choices=[('LUXURY', 'Luxury'), ('ECONOMY', 'Economy')], max_length=20)),
                ('led_strip_rate_per_mm', models.DecimalField(decimal_places=4, max_digits=8)),
                ('spot_light_rate_per_cabinet', models.DecimalField(decimal_places=2, max_digits=8)),
                ('led_specification', models.TextField()),
                ('spot_light_specification', models.TextField()),
                ('cabinet_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.materials')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lighting', to='pricing.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
