# Generated by Django 5.1.3 on 2025-08-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_customer_status_customer_is_active'),
        ('pricing', '0002_lightingrules_projectlighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightingrules',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='lightingrules',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectlighting',
            unique_together={('project', 'cabinet_material', 'lighting_tier')},
        ),
    ]
