# Generated by Django 5.1.3 on 2025-08-26 18:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_customer_status_customer_is_active'),
        ('pricing', '0003_lightingrules_customer_lightingrules_is_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightingrules',
            name='cabinet_type',
            field=models.ForeignKey(blank=True, help_text='Specific cabinet type (optional - leave blank for all types)', null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.cabinettypes'),
        ),
        migrations.AlterField(
            model_name='lightingrules',
            name='led_strip_rate_per_mm',
            field=models.DecimalField(decimal_places=4, default=Decimal('2.0'), max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='lightingrules',
            unique_together={('customer', 'cabinet_material', 'cabinet_type', 'budget_tier', 'effective_from')},
        ),
        migrations.CreateModel(
            name='ProjectLightingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_top_length_mm', models.IntegerField(default=0, help_text='Total work top length for nosing LEDs')),
                ('total_wall_cabinet_width_mm', models.IntegerField(default=0)),
                ('total_base_cabinet_width_mm', models.IntegerField(default=0)),
                ('total_wall_cabinet_count', models.IntegerField(default=0)),
                ('grand_total_lighting_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_config', to='pricing.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLightingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wall_cabinet_width_mm', models.IntegerField(default=0)),
                ('base_cabinet_width_mm', models.IntegerField(default=0)),
                ('wall_cabinet_count', models.IntegerField(default=0)),
                ('work_top_length_mm', models.IntegerField(default=0)),
                ('led_under_wall_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('led_work_top_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('led_skirting_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spot_lights_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('cabinet_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.materials')),
                ('cabinet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.cabinettypes')),
                ('lighting_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.lightingrules')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_items', to='pricing.project')),
            ],
            options={
                'unique_together': {('project', 'cabinet_material', 'cabinet_type')},
            },
        ),
        migrations.DeleteModel(
            name='ProjectLighting',
        ),
    ]
