# Generated by Django 5.1.3 on 2025-08-29 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productvariant_image_alter_productvariant_color_name_and_more'),
        ('pricing', '0004_lightingrules_cabinet_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlineitemaccessory',
            options={'ordering': ['line_item', 'id']},
        ),
        migrations.AddField(
            model_name='projectlineitemaccessory',
            name='installation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectlineitemaccessory',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant'),
        ),
        migrations.AlterField(
            model_name='projectlineitemaccessory',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pricing.accessories'),
        ),
        migrations.AlterUniqueTogether(
            name='projectlineitemaccessory',
            unique_together={('line_item', 'product_variant')},
        ),
    ]
