# Generated by Django 5.1.3 on 2025-08-29 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productvariant_image_alter_productvariant_color_name_and_more'),
        ('pricing', '0005_alter_projectlineitemaccessory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlineitemaccessory',
            name='accessory',
        ),
        migrations.AlterField(
            model_name='projectlineitemaccessory',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant'),
            preserve_default=False,
        ),
    ]
