# Generated by Django 5.1.3 on 2025-08-29 15:20

import django.db.models.deletion
import pricing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_remove_accessory_finalize_product_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectplanimage',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='projectplanimage',
            name='project',
        ),
        migrations.AddField(
            model_name='projectplanimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='projectplanimage',
            name='file_type',
            field=models.CharField(blank=True, help_text='File MIME type', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectplanimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Image caption or description', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectplanimage',
            name='image',
            field=models.ImageField(help_text='Plan image file (JPG, PNG, PDF supported)', upload_to=pricing.models.plan_image_upload_path),
        ),
        migrations.AlterField(
            model_name='projectplanimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for displaying images within group'),
        ),
        migrations.CreateModel(
            name='ProjectPlanImageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text="Group heading (e.g., 'Floor Plans', '3D Renderings')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of this image group')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying groups')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_groups', to='pricing.project')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'unique_together': {('project', 'title')},
            },
        ),
        migrations.AddField(
            model_name='projectplanimage',
            name='image_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pricing.projectplanimagegroup'),
            preserve_default=False,
        ),
    ]
