# Generated by Django 5.1.3 on 2024-12-07 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('kitchen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[('Lead', 'Lead'), ('Pipeline', 'Pipeline'), ('Design', 'Design'), ('Confirmation', 'Confirmation'), ('Production', 'Production'), ('Installation', 'Installation'), ('Sign Out', 'Sign Out')], default='Lead', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
