# Generated by Django 5.1.3 on 2025-01-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_document_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kitchen',
            field=models.FloatField(),
        ),
    ]
