# Generated by Django 5.1.3 on 2025-01-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_kitchen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='tall_unit_motorised',
            new_name='lavido_pullout',
        ),
    ]
