# Generated by Django 5.1.3 on 2025-01-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_tall_unit_motorised_requirement_lavido_pullout'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='handle_color_black',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='inbuilt_handles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='sink_base_wastebin_pullout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='sink_multifunction',
            field=models.BooleanField(default=False),
        ),
    ]
