# Generated by Django 5.1.3 on 2025-01-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_requirement_handle_color_black_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='', help_text='Enter the name/title for the document.', max_length=255),
            preserve_default=False,
        ),
    ]
