# Generated by Django 5.1.3 on 2025-01-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(choices=[('site_photos_and_measurements', 'Site Photos and Measurements'), ('plan_and_elevation', 'Plan and Elevation'), ('3d', '3D'), ('ept', 'EPT'), ('factory_quotation', 'Factory Quotation'), ('client_quotation', 'Client Quotation'), ('appliances', 'Appliances'), ('counter_tops_with_sink_and_faucet', 'Counter Tops with Sink and Faucet'), ('site_completion_photos', 'Site Completion Photos')], default='site_photos_and_measurements', help_text='Select the name/title for the document.', max_length=255),
        ),
    ]
