# Generated by Django 5.1.3 on 2025-01-27 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_document_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='kitchen',
        ),
        migrations.CreateModel(
            name='KitchenType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WPC', 'WPC'), ('SS', 'Stainless Steel'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('count', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_types', to='customers.customer')),
            ],
        ),
    ]
