# Generated by Django 5.1.3 on 2025-08-30 11:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0007_alter_projectplanimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationPDFTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('STANDARD', 'Standard Quotation'), ('DETAILED', 'Detailed with Images'), ('SIMPLE', 'Simple Layout')], default='DETAILED', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationPDFCustomization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('include_cabinet_details', models.BooleanField(default=True)),
                ('include_door_details', models.BooleanField(default=True)),
                ('include_accessories', models.BooleanField(default=True)),
                ('include_accessory_images', models.BooleanField(default=True)),
                ('include_plan_images', models.BooleanField(default=True)),
                ('include_lighting', models.BooleanField(default=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_reason', models.CharField(blank=True, max_length=200)),
                ('special_instructions', models.TextField(blank=True)),
                ('installation_notes', models.TextField(blank=True)),
                ('timeline_notes', models.TextField(blank=True)),
                ('custom_requirements', models.TextField(blank=True)),
                ('show_item_codes', models.BooleanField(default=True)),
                ('show_dimensions', models.BooleanField(default=True)),
                ('include_warranty_info', models.BooleanField(default=True)),
                ('include_terms_conditions', models.BooleanField(default=True)),
                ('selected_plan_images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_customizations', to='pricing.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotation_pdf.quotationpdftemplate')),
            ],
            options={
                'unique_together': {('project', 'template')},
            },
        ),
        migrations.CreateModel(
            name='QuotationPDFHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent to Customer'), ('APPROVED', 'Approved by Customer'), ('EXPIRED', 'Expired')], default='GENERATED', max_length=20)),
                ('customization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation_pdf.quotationpdfcustomization')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_history', to='pricing.project')),
            ],
        ),
    ]
