# Generated by Django 5.1.3 on 2025-08-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationpdftemplate',
            name='template_file',
            field=models.CharField(blank=True, default='quotation_pdf/detailed_quotation.html', help_text='Path to template file relative to templates directory', max_length=255),
        ),
    ]
