# Generated by Django 5.1.3 on 2025-01-21 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_document_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionInstallationPhase',
            fields=[
                ('phase_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epd_received', models.BooleanField(default=False)),
                ('epd_sharing_site_visit', models.BooleanField(default=False)),
                ('flooring_completed', models.BooleanField(default=False)),
                ('ceiling_completed', models.BooleanField(default=False)),
                ('carcass_at_site', models.BooleanField(default=False)),
                ('countertop_at_site', models.BooleanField(default=False)),
                ('shutters_at_site', models.BooleanField(default=False)),
                ('carcass_installed', models.BooleanField(default=False)),
                ('countertop_installed', models.BooleanField(default=False)),
                ('shutters_installed', models.BooleanField(default=False)),
                ('appliances_received_at_site', models.BooleanField(default=False)),
                ('appliances_installed', models.BooleanField(default=False)),
                ('light_installed', models.BooleanField(default=False)),
                ('handover_to_client', models.BooleanField(default=False)),
                ('client_feedback_photography', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_installation_phases', to='customers.customer')),
            ],
        ),
    ]
