# Generated by Django 5.1.3 on 2025-08-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_code',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='material_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
