# Generated by Django 5.1.3 on 2025-08-17 17:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_material_remove_product_material_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Final value/selling price - enter manually', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='material_code',
            field=models.CharField(help_text='Enter material code manually', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
