# Generated by Django 5.1.3 on 2025-08-18 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productvariant_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit/sqft', max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Cabinet Material',
                'verbose_name_plural': 'Cabinet Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CabinetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sqft_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per square foot', max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Cabinet Type',
                'verbose_name_plural': 'Cabinet Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit/sqft', max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Door Material',
                'verbose_name_plural': 'Door Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShutterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sqft_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per square foot', max_digits=10, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price (column 5 in Excel)', max_digits=10, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Tax percentage (column 6 in Excel)', max_digits=5, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (column 7 in Excel)', max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Shutter Type',
                'verbose_name_plural': 'Shutter Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CabinetShutterCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default shutter for this cabinet type?')),
                ('cabinet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cabinettype')),
                ('shutter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.shuttertype')),
            ],
            options={
                'verbose_name': 'Cabinet Shutter Compatibility',
                'verbose_name_plural': 'Cabinet Shutter Compatibilities',
                'unique_together': {('cabinet_type', 'shutter_type')},
            },
        ),
    ]
