# Generated by Django 5.1.3 on 2025-08-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_quotation_options_alter_quotation_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='carcass_material',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='shutter_material',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationaccessory',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationplan',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationsummary',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationtimeline',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='workingkitchensection',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationaccessory',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='cabinet_type',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product_variant',
        ),
        migrations.DeleteModel(
            name='OpenKitchenSection',
        ),
        migrations.DeleteModel(
            name='QuotationPlan',
        ),
        migrations.DeleteModel(
            name='QuotationSummary',
        ),
        migrations.DeleteModel(
            name='QuotationTimeline',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='WorkingKitchenSection',
        ),
        migrations.DeleteModel(
            name='QuotationAccessory',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
