# Generated by Django 5.1.3 on 2025-08-24 15:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_quotation_carcass_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('accessory_type', models.CharField(blank=True, max_length=50)),
                ('price_type', models.CharField(choices=[('FIXED', 'FIXED'), ('PER_UNIT', 'PER_UNIT')], default='FIXED', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CabinetTypeBrandCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('standard_accessory_charge', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CabinetTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_depth_mm', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoorFinishRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinishRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('budget_tier', models.CharField(choices=[('LUXURY', 'LUXURY'), ('ECONOMY', 'ECONOMY')], max_length=10)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeometryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('formula_cabinet_sqft', models.TextField()),
                ('formula_door_sqft', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('cabinet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geometry_rules', to='catalog.cabinettypes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LightingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('calc_method', models.CharField(choices=[('FLAT', 'FLAT'), ('PER_WIDTH', 'PER_WIDTH'), ('PER_LM', 'PER_LM'), ('PER_SQFT', 'PER_SQFT')], default='FLAT', max_length=10)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('scale_basis', models.CharField(default='NONE', max_length=20)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('role', models.CharField(choices=[('CABINET', 'CABINET'), ('DOOR', 'DOOR'), ('TOP', 'TOP'), ('BOTH', 'BOTH')], default='BOTH', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('budget_tier', models.CharField(choices=[('LUXURY', 'LUXURY'), ('ECONOMY', 'ECONOMY')], max_length=10)),
                ('brand_name', models.CharField(max_length=100)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=5)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('QUOTED', 'QUOTED'), ('CONFIRMED', 'CONFIRMED'), ('IN_PRODUCTION', 'IN_PRODUCTION'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('width_mm', models.PositiveIntegerField()),
                ('depth_mm', models.PositiveIntegerField()),
                ('height_mm', models.PositiveIntegerField()),
                ('computed_cabinet_sqft', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('computed_door_sqft', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('cabinet_unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('door_unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cabinet_material_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('standard_accessory_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('lighting_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('door_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('top_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('line_total_before_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('remarks', models.TextField(blank=True)),
                ('cabinet_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_cabinet_material', to='catalog.materials')),
                ('cabinet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.cabinettypes')),
                ('door_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_door_material', to='catalog.materials')),
                ('lighting_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.lightingrule')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLineItemAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.accessories')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_accessories', to='catalog.projectlineitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subtotal_cabinets', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('subtotal_doors', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('subtotal_accessories', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('subtotal_tops', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='catalog.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CabinetMaterial',
        ),
        migrations.AlterUniqueTogether(
            name='cabinetshuttercompatibility',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cabinetshuttercompatibility',
            name='cabinet_type',
        ),
        migrations.RemoveField(
            model_name='cabinetshuttercompatibility',
            name='shutter_type',
        ),
        migrations.DeleteModel(
            name='DoorMaterial',
        ),
        migrations.RemoveField(
            model_name='productpricehistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='productpricehistory',
            name='product_variant',
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='cabinettypebrandcharge',
            name='cabinet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_charges', to='catalog.cabinettypes'),
        ),
        migrations.AddField(
            model_name='finishrates',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cabinet_rates', to='catalog.materials'),
        ),
        migrations.AddField(
            model_name='doorfinishrates',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='door_rates', to='catalog.materials'),
        ),
        migrations.DeleteModel(
            name='CabinetType',
        ),
        migrations.DeleteModel(
            name='CabinetShutterCompatibility',
        ),
        migrations.DeleteModel(
            name='ShutterType',
        ),
        migrations.DeleteModel(
            name='ProductPriceHistory',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.AlterUniqueTogether(
            name='cabinettypebrandcharge',
            unique_together={('cabinet_type', 'brand_name', 'effective_from')},
        ),
        migrations.AlterUniqueTogether(
            name='finishrates',
            unique_together={('material', 'budget_tier', 'effective_from')},
        ),
        migrations.AlterUniqueTogether(
            name='doorfinishrates',
            unique_together={('material', 'effective_from')},
        ),
    ]
