# Generated by Django 5.1.3 on 2025-08-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_accessories_cabinettypebrandcharge_cabinettypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinettypes',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this cabinet type belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category'),
        ),
    ]
