# Generated by Django 5.1.3 on 2025-08-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_cabinettypes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinettypes',
            name='default_depth_mm',
        ),
    ]
