# Generated by Django 5.1.3 on 2025-08-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_cabinettypes_default_depth_mm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlineitemaccessory',
            name='accessory',
        ),
        migrations.AlterUniqueTogether(
            name='cabinettypebrandcharge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cabinettypebrandcharge',
            name='cabinet_type',
        ),
        migrations.RemoveField(
            model_name='cabinettypes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='geometryrule',
            name='cabinet_type',
        ),
        migrations.RemoveField(
            model_name='projectlineitem',
            name='cabinet_type',
        ),
        migrations.AlterUniqueTogether(
            name='doorfinishrates',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doorfinishrates',
            name='material',
        ),
        migrations.AlterUniqueTogether(
            name='finishrates',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='finishrates',
            name='material',
        ),
        migrations.RemoveField(
            model_name='projectlineitem',
            name='lighting_rule',
        ),
        migrations.RemoveField(
            model_name='projectlineitem',
            name='door_material',
        ),
        migrations.RemoveField(
            model_name='projectlineitem',
            name='cabinet_material',
        ),
        migrations.RemoveField(
            model_name='projecttotals',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectlineitem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectlineitemaccessory',
            name='line_item',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='CabinetTypeBrandCharge',
        ),
        migrations.DeleteModel(
            name='GeometryRule',
        ),
        migrations.DeleteModel(
            name='CabinetTypes',
        ),
        migrations.DeleteModel(
            name='DoorFinishRates',
        ),
        migrations.DeleteModel(
            name='FinishRates',
        ),
        migrations.DeleteModel(
            name='LightingRule',
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
        migrations.DeleteModel(
            name='ProjectTotals',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectLineItem',
        ),
        migrations.DeleteModel(
            name='ProjectLineItemAccessory',
        ),
    ]
