# Generated by Django 5.1.3 on 2025-08-28 06:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_projectlineitemaccessory_accessory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'material_code']},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'material_code')},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_name',
            field=models.CharField(default=1, help_text='Color name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='company_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final company price (auto-calculated: MRP + Tax - Discount)', max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated discount amount (auto-calculated)', max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Depth in mm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in mm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_width',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Width in mm', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated tax amount (auto-calculated)', max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Tax percentage (default 18%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='mrp',
            field=models.DecimalField(decimal_places=2, help_text='Maximum Retail Price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='custom_depth',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='custom_height',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='custom_width',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='value',
        ),
    ]
