# Generated by Django 5.1.3 on 2025-08-28 07:23

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary image for this variant', null=True, upload_to=catalog.models.variant_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_name',
            field=models.CharField(blank=True, help_text='Color name (e.g., Stainless Steel Silver)', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in mm', max_digits=8, null=True),
        ),
    ]
