# Generated by Django 5.1.3 on 2025-09-15 01:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productvariant_image_alter_productvariant_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='company_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final company price (auto-calculated: MRP - Discount)', max_digits=10),
        ),
    ]
