# Generated by Django 5.1.3 on 2025-08-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_workflowhistory_changed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('leads_count', models.IntegerField(default=0)),
                ('pipeline_count', models.IntegerField(default=0)),
                ('design_count', models.IntegerField(default=0)),
                ('production_count', models.IntegerField(default=0)),
                ('installation_count', models.IntegerField(default=0)),
                ('total_customers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlySnapshot',
        ),
        migrations.AlterModelOptions(
            name='workflowhistory',
            options={'ordering': ['-timestamp']},
        ),
    ]
