# Generated by Django 5.1.3 on 2025-02-05 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('architect_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Architect Name')),
                ('firm', models.CharField(max_length=255, verbose_name='Firm')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('principal_architect_name', models.CharField(max_length=255, verbose_name='Principal Architect Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
